image: docker:stable

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  REPOSITORY_URL: 084476933205.dkr.ecr.us-east-1.amazonaws.com/dsl-node-api
  

services:
  - docker:dind

before_script:
  - docker info
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  
stages:
  #- test
  - build

#test:
#  stage: test
#  services:
#    - mongo
#  script:
#    - npm install yarn
#    - yarn
#    - yarn test

build:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  only:
    - master
